# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Tools
version:      0.02
version_from: lib/GPS/Tools.pm
installdirs:  site
requires:
    Device::SerialPort:            0
    Exporter:                      0
    Math::Trig:                    0
    POSIX:                         0
    strict:                        0
    Time::HiRes:                   0
    vars:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
